use_frameworks!

platform :ios, '10.0'

target 'EsTool_Example' do
  pod 'EsTool', :path => '../'

  target 'EsTool_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end
